# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lvrossem/Documents/emulators/nes-emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lvrossem/Documents/emulators/nes-emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lvrossem/Documents/emulators/nes-emulator/CMakeFiles /home/lvrossem/Documents/emulators/nes-emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lvrossem/Documents/emulators/nes-emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NES

# Build rule for target.
NES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NES
.PHONY : NES

# fast build rule for target.
NES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/build
.PHONY : NES/fast

src/cpu.o: src/cpu.cpp.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/cpu_memory.o: src/cpu_memory.cpp.o

.PHONY : src/cpu_memory.o

# target to build an object file
src/cpu_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu_memory.cpp.o
.PHONY : src/cpu_memory.cpp.o

src/cpu_memory.i: src/cpu_memory.cpp.i

.PHONY : src/cpu_memory.i

# target to preprocess a source file
src/cpu_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu_memory.cpp.i
.PHONY : src/cpu_memory.cpp.i

src/cpu_memory.s: src/cpu_memory.cpp.s

.PHONY : src/cpu_memory.s

# target to generate assembly for a file
src/cpu_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/cpu_memory.cpp.s
.PHONY : src/cpu_memory.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nes.o: src/nes.cpp.o

.PHONY : src/nes.o

# target to build an object file
src/nes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/nes.cpp.o
.PHONY : src/nes.cpp.o

src/nes.i: src/nes.cpp.i

.PHONY : src/nes.i

# target to preprocess a source file
src/nes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/nes.cpp.i
.PHONY : src/nes.cpp.i

src/nes.s: src/nes.cpp.s

.PHONY : src/nes.s

# target to generate assembly for a file
src/nes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/nes.cpp.s
.PHONY : src/nes.cpp.s

src/ppu.o: src/ppu.cpp.o

.PHONY : src/ppu.o

# target to build an object file
src/ppu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/ppu.cpp.o
.PHONY : src/ppu.cpp.o

src/ppu.i: src/ppu.cpp.i

.PHONY : src/ppu.i

# target to preprocess a source file
src/ppu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/ppu.cpp.i
.PHONY : src/ppu.cpp.i

src/ppu.s: src/ppu.cpp.s

.PHONY : src/ppu.s

# target to generate assembly for a file
src/ppu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NES.dir/build.make CMakeFiles/NES.dir/src/ppu.cpp.s
.PHONY : src/ppu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NES"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/cpu_memory.o"
	@echo "... src/cpu_memory.i"
	@echo "... src/cpu_memory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nes.o"
	@echo "... src/nes.i"
	@echo "... src/nes.s"
	@echo "... src/ppu.o"
	@echo "... src/ppu.i"
	@echo "... src/ppu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

